version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

before_build:
  - nuget restore
  - ps: .\Build\Replace-FileString -Pattern '\$version\$' -Replacement "$env:appveyor_build_version" -Path .\src\Foundatio.nuspec -Overwrite
  - ps: .\Build\Replace-FileString -Pattern '\$version\$' -Replacement "$env:appveyor_build_version" -Path .\src\Foundatio.Redis.nuspec -Overwrite
  - ps: .\Build\Replace-FileString -Pattern '\$version\$' -Replacement "$env:appveyor_build_version" -Path .\src\Foundatio.Azure.nuspec -Overwrite
  - ps: .\Build\Replace-FileString -Pattern '\$version\$' -Replacement "$env:appveyor_build_version" -Path .\src\Foundatio.StatsD.nuspec -Overwrite

configuration: Release

build:
  project: Foundatio.sln
  publish_nuget: true
  publish_nuget_symbols: true

after_build:
  - cinst redis-64
  - redis-server --service-install
  - redis-server --service-start

deploy:
  - provider: Environment
    name: NuGet
