version: 4.3.{build}
os: Visual Studio 2017 RC
clone_depth: 2
configuration: Release

pull_requests:
  do_not_increment_build_number: true

init: 
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_BRANCH" -ne "master") { $env:VERSION_SUFFIX="pre" }

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - ps: dotnet build -f net46 Foundatio.sln /p:VersionPrefix="$($env:APPVEYOR_BUILD_VERSION)" /p:VersionSuffix="$($env:VERSION_SUFFIX)"

before_test:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - choco install rabbitmq --ignoredependencies -y
  - ps: (Get-Service -Name RabbitMQ).Status
  - ps: |
      $msiPath = "$env:TEMP\MicrosoftAzureStorageEmulator.msi"
      (New-Object Net.WebClient).DownloadFile('http://download.microsoft.com/download/8/B/9/8B905834-DA6B-4A0A-A6C2-C1B8ACD9141D/MicrosoftAzureStorageEmulator.msi', $msiPath)
      cmd /c start /wait msiexec /i $msiPath /quiet
      del $msiPath

artifacts:
  - path: artifacts\*.nupkg
    name: ReleaseArtifacts

deploy:
  - provider: Environment
    name: NuGet
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: GniMpFE62HprSyQNQoej/fBOAdbQe8EMWAMMNXX0s2JxeNePjemiO1bCf4eYweE4p70mm0sCwMjeEP/Ps9aTMA==
    channel: '#notifications'
