version: 5.0.{build}
os: Visual Studio 2017
clone_depth: 2
configuration: Release

pull_requests:
  do_not_increment_build_number: true

init: 
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_BRANCH" -ne "master") { $env:VERSION_SUFFIX="pre" }

before_build:
  - ps: |
      [xml]$versionXml = Get-Content .\build\version.props
      $versionXml.Project.PropertyGroup.VersionPrefix = "$($env:APPVEYOR_BUILD_VERSION)"
      $versionXml.Project.PropertyGroup.VersionSuffix = "$($env:VERSION_SUFFIX)"
      $versionXml.Save("$pwd\build\version.props")
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - ps: dotnet pack -c Release

before_test:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - choco install rabbitmq --ignoredependencies -y
  - ps: (Get-Service -Name RabbitMQ).Status

artifacts:
  - path: artifacts\*.nupkg
    name: ReleaseArtifacts

deploy:
  - provider: Environment
    name: NuGet
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: GniMpFE62HprSyQNQoej/fBOAdbQe8EMWAMMNXX0s2JxeNePjemiO1bCf4eYweE4p70mm0sCwMjeEP/Ps9aTMA==
    channel: '#notifications'
