version: 1.0.{build}
clone_depth: 2

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

before_build:
  - nuget restore
  - ps: .\Build\Replace-FileString -Pattern '\$version\$' -Replacement "$env:appveyor_build_version" -Path src\**\*.nuspec -Overwrite

configuration: Release

build:
  project: Foundatio.sln
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

cache:
#  - packages -> **\packages.config

before_test:
  - cinst redis-64
  - redis-server --service-install
  - redis-server --service-start
  - ps: '& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Azure\Storage Emulator\WAStorageEmulator.exe" start'
#  - ps: Build\enable-rdp.ps1

deploy:
  - provider: Environment
    name: Exceptionless NuGet
