version: 4.3.{build}
os: Visual Studio 2017 RC
clone_depth: 2
configuration: Release

pull_requests:
  do_not_increment_build_number: true

init: 
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_BRANCH" -ne "master") { $env:VERSION_SUFFIX="-pre" }

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Foundatio.sln /p:VersionPrefix={version} /p:VersionSuffix=$env:VERSION_SUFFIX /p:GeneratePackageOnBuild=false

before_test:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - choco install rabbitmq --ignoredependencies -y
  - ps: (Get-Service -Name RabbitMQ).Status

after_test:
  - ps: >-
      DIR "src/*" | Where {$_.PsIsContainer} | ForEach {
        dotnet pack "$_" -c Release -o .\artifacts\
      }

artifacts:
  - path: artifacts\*.nupkg
    name: ReleaseArtifacts

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: GniMpFE62HprSyQNQoej/fBOAdbQe8EMWAMMNXX0s2JxeNePjemiO1bCf4eYweE4p70mm0sCwMjeEP/Ps9aTMA==
    channel: '#notifications'
